# Generated by Django 4.0.4 on 2022-05-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
