# Generated by Django 4.0.4 on 2022-06-01 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0007_alter_holiday_date_alter_holiday_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_alter_booking_created_by_alter_booking_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(help_text='Fecha reservada.', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(help_text='Hora final del intervalo disponible en el día.', verbose_name='Hora final'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(help_text='Horario seleccionado.', on_delete=django.db.models.deletion.CASCADE, to='conf.schedule', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(help_text='Hora inicial del intervalo disponible en el día determinado.', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='Usuario al que corresponde la reserva.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
