# Generated by Django 4.0.4 on 2022-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'El correo ingresado ya existe.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
