# Generated by Django 4.0.4 on 2022-05-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_holiday_updated_by_schedule_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(error_messages={'unique': 'A holiday with that date already exists.'}, unique=True),
        ),
    ]
