# Generated by Django 4.0.4 on 2022-06-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0006_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(error_messages={'unique': 'A holiday with that date already exists.'}, help_text='Fecha correspondiente del feriado.', unique=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(blank=True, help_text='Nombre del evento celebrado en el día festivo.', max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el feriado está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], help_text='Día de la semana (1-7 : Lunes - Domingo)', max_length=1, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(help_text='Hora final del intervalo disponible en el día', verbose_name='Hora final'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='space',
            field=models.ForeignKey(help_text='Espacio al que corresponde el horario.', on_delete=django.db.models.deletion.CASCADE, to='conf.space', verbose_name='Espacio'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(help_text='Hora inicial del intervalo disponible en el día', verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(help_text='Cantidad informativa de la capacidad de asistentes de la sala', verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='space',
            name='daily_max_bookings',
            field=models.IntegerField(blank=True, help_text='Máximo de reservas en el día por usuario', null=True, verbose_name='Reservas máx. por día'),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción del espacio.', max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='space',
            name='increments',
            field=models.IntegerField(help_text='Intervalos de tiempo para mostrar los horarios establecidos para el espacio (minutos)', verbose_name='Incremento'),
        ),
        migrations.AlterField(
            model_name='space',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el espacio está habilitado para reservar.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='space',
            name='max_booking_days',
            field=models.IntegerField(help_text='Tiempo máximo en el que un usuario puede crear una reserva en el futuro (días)', verbose_name='Días máx. para reservar'),
        ),
        migrations.AlterField(
            model_name='space',
            name='max_spots',
            field=models.IntegerField(help_text='Número máximo de reservas simultáneas permitidas en un intérvalo o rango de tiempo.', verbose_name='Espacios disponibles'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(help_text='Nombre designado a la sala o espacio.', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='space',
            name='time_by_range',
            field=models.BooleanField(default=False, help_text='Determina el modo de selección de tiempo al momento de realizar una reserva', verbose_name='Reserva por rango'),
        ),
        migrations.AlterField(
            model_name='space',
            name='weekly_max_bookings',
            field=models.IntegerField(blank=True, help_text='Máximo de reservas en la semana por usuario', null=True, verbose_name='Reservas máx. por semana'),
        ),
    ]
