# Generated by Django 4.0.4 on 2022-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0008_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(error_messages={'unique': 'Ya existe un día festivo en la fecha seleccionada.'}, help_text='Fecha correspondiente del feriado.', unique=True, verbose_name='Fecha'),
        ),
    ]
