# Generated by Django 4.0.4 on 2022-06-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('conf', '0009_alter_holiday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos asociados al horario.', to='auth.group', verbose_name='Grupos'),
        ),
    ]
