# Generated by Django 4.0.4 on 2022-05-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_holiday_rename_events_event_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
        migrations.RenameModel(
            old_name='Holiday',
            new_name='Holidays',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Schedules',
        ),
    ]
